# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra', '~> 1.4.7'
gem 'puma', '~> 3.4.0'
gem 'jwt', '~> 2.3.0'
gem "openssl"
gem 'redis'
